### ISSUE TITLE
Missing css document

### ISSUE THREAD

**Issue by Grotgod** [chemoish/videojs-chapter-thumbnails#9]
The "Getting started" section refers to a css file "videojs.chapter-thumbnails.min.css".
This file has not been included in the package.

A "dist" folder with this css file and the js files would have been a nice.

**Comment by chemoish** [comment]
@Grotgod 

``` bash
npm i videojs-chapter-thumbnails

ls -la node_modules/videojs-chapter-thumbnails/dist
```

It is available through `npm`, but I do not commit the `dist` directory.

**Comment by chemoish** [comment]
Closing issue. Can reopen if there are still questions.
